### ISSUE TITLE
Dismissing item issue

### ISSUE THREAD

**Issue by yRerikh** [rundfunk47/stinsen#111]
Hello, @rundfunk47, thank you for this framework.
I would like to ask you about some moment while dismissing an item manually.
When an item is presented with parameter @Root(.modal), there is a possibility to dismiss it by swiping down without pressing any button.
My problem is that I don't know how to detect dismiss event in such case.
Could you help me with that?

**Comment by LePips** [comment]
There are two ways to achieve this:

- SwiftUI way: Use `onDisappear` on the presented view
- Stinsen way: I assume you are presenting a view, so instead wrap that view in a new coordinator and have your view call `.dismissCoordinator()` on the `Router` object, as the dismissal allows an optional `action` parameter.

**Comment by yRerikh** [comment]
@LePips I suppose, a parameter _onDismiss_ is exactly what I need. Thank you very much.
