### ISSUE TITLE
How to implement Deep-link

### ISSUE THREAD

**Issue by PangMo5** [rundfunk47/stinsen#14]
First of all, thank you for creating a great library.

I'm using this library to implement Deep-link.

Deep-link need to be able to work on any screen, so we'll need a coordinator that can be used for any screen.
Is this possible?

I'd appreciate it if you could let me know if there's any other way besides the one I said.

Thanks.

**Comment by rundfunk47** [comment]
Hi!

If you mean you need to navigate to every screen in the app through deep links, yes, that would be correct. You can also create a "tree", so for instance if your deep link needs to open a specific tab and navigate from that, that should also be possible.

**Comment by PangMo5** [comment]
Thank you for your answer.

In fact, I don't need a tree, I just wanted to Deep-links from the first screen to any screen using recycle the coordinator that I made before.

But I don't know if it's the nature of EnvironmentObject. 
In `View` created by `Start()` of `ACoodinator`, only `ACoodinator` works and attempts to access other coordinators, such as `BCoodinator`, results in the following error:

```
SwiftUI:0: Fatal error: No ObservableObject of type NavigationRouter<Route> found. 
A View.environmentObject(_:) for NavigationRouter<Route> may be missing as an ancestor of this view.
```

Codes are roughly like this.

```swift
final class ACoordinator: NavigationCoordinatable {
    var navigationStack = NavigationStack()

    enum Route: NavigationRoute {
        case b
    }

    func resolveRoute(route: Route) -> Transition {
        switch route {
        case .b:
            return .modal(NavigationViewCoordinator(BCoordinator()).eraseToAnyCoordinatable())
        }
    }

    @ViewBuilder
    func start() -> some View {
        AView()
    }
}

struct View: View {

    @EnvironmentObject var aRouter: NavigationRouter<ACoordinator.Route>
    @EnvironmentObject var bRouter: NavigationRouter<BCoordinator.Route>
    
    var body: some View {
	    VStack {
    		Button {
    		// Works well
    			aRouter.route(to: .b)
    		} label: {
	    		Text("TestA")
    		}
    		Button {
    		// Crash
    			bRouter.route(~~~
    		} label: {
	    		Text("TestB")
    		}
    	}
    }
}
```

If this is intended, what structure should I fill out to do what I want?

**Comment by rundfunk47** [comment]
Oops. I realized there is no way to initialize NavigationStack with a coordinator yet. I've created an issue:

https://github.com/rundfunk47/stinsen/issues/16

**Comment by PangMo5** [comment]
Thank you for your kind answer.

**Comment by rundfunk47** [comment]
Hi! There's a version 2.0.0 now that supports deep-links. Please try it out and see if you can use it in your project :)

**Comment by PangMo5** [comment]
Thank you so much! I'll try it 😆
