### ISSUE TITLE
Modal transition doesn't work on iOS 14.0 – 14.4

### ISSUE THREAD

**Issue by Soloqub** [rundfunk47/stinsen#17]
It can be reproduced on the sample app. On iOS 14.5 and greater push and modal transitions work well.
On iOS 14.0 – 14.4 push works well, but modal doesn't.

**Comment by rundfunk47** [comment]
Confirmed. Root cause seems to be a bug before 14.5 which doesn't allow FullscreenCover and Sheet on the same view.

**Comment by rundfunk47** [comment]
Fixed with https://github.com/rundfunk47/stinsen/commit/65eb847aeff796721e1e6650af57ca720dcde6a0 , can you confirm the fix works @Soloqub ?

**Comment by Soloqub** [comment]
@rundfunk47 Yes, it fixed now. 
Thanks a lot!
