### ISSUE TITLE
How to create a custom TabCoordinatable

### ISSUE THREAD

**Issue by jblanco-applaudostudios** [rundfunk47/stinsen#18]
Is there any way to create a custom `TabCoordinatable`?
What I want is basically the function of menu changing, but I don't want the coordinator's view to be a tab view, but a custom menu instead.

I had a look at the source and tried to create my own protocol, but I'm getting several error messages stating that the `children.dismissalAction` is unaccessible due to internal protection level. 

Any way to implement this?

**Comment by rundfunk47** [comment]
Hi! At the moment it's a bit involved but it can absolutely be done. For instance, this is the code I use to create a "hamburger menu":

```

public class HamburgerChild: ObservableObject {
    @Published var childCoordinators: [AnyCoordinatable]
    var dismissalAction: DismissalAction
    @Published public var showMenu: Bool = false

    public init(detail: AnyCoordinatable, master: AnyCoordinatable?) {
        self.childCoordinators = [detail, master].compactMap { $0 }
        self.dismissalAction = {}
    }
}


public protocol HamburgerCoordinatable: Coordinatable {
    associatedtype Route
    associatedtype Start: View
    func resolveRoute(route: Route) -> AnyCoordinatable
    @ViewBuilder func start() -> Start
    var children: HamburgerChild { get }
}

public extension HamburgerCoordinatable {
    var childCoordinators: [AnyCoordinatable] {
        return children.childCoordinators
    }
    
    var dismissalAction: DismissalAction {
        get {
            children.dismissalAction
        } set {
            children.dismissalAction = newValue
        }
    }
    
    func coordinatorView() -> AnyView {
        return AnyView(
            HamburgerCoordinatableView(coordinator: self)
        )
    }
    
    func dismissChildCoordinator(_ childCoordinator: AnyCoordinatable, _ completion: (() -> Void)?) {
        fatalError("not implemented")
    }
}


struct HamburgerCoordinatableView<T: HamburgerCoordinatable>: View {
    var coordinator: T
    let router: HamburgerRouter<T.Route>
    @ObservedObject var children: HamburgerChild
    
    init(coordinator: T) {
        self.router = HamburgerRouter(coordinator)
        self.coordinator = coordinator
        self.children = coordinator.children
    }
    
    public var overlay: some View {
        ZStack {
            Color.black.opacity(!router.showMenu ? 0 : 0.6).edgesIgnoringSafeArea(.all)
            if router.showMenu {
                Color.black.opacity(!router.showMenu ? 0 : 0.0006).edgesIgnoringSafeArea(.all).onTapGesture {
                    router.showMenu = false
                }
            }
        }
        .animation(.easeOut(duration: 0.25))
    }
    
    var body: some View {
        return GeometryReader { geometry in
            ZStack(alignment: .topLeading) {
                if coordinator.childCoordinators.dropFirst().first != nil {
                    coordinator.childCoordinators[1].coordinatorView()
                        .overlay(overlay)
                } else {
                    coordinator.start()
                        .overlay(overlay)
                }
                coordinator
                    .childCoordinators[0]
                    .coordinatorView()
                    .frame(width: 290)
                    .offset(x: !router.showMenu ? -290 : 0, y: 0)
                    .animation(.easeOut(duration: 0.25))
            }
        }
        .environmentObject(router)
    }
}

class HamburgerRoutable {
    var _anyRoute: (Any) -> Void
    
    func anyRoute(to route: Any) {
        _anyRoute(route)
    }
    
    init<T: HamburgerCoordinatable>(coordinator: T) {
        _anyRoute = { viewRoute in
            let resolved = coordinator.resolveRoute(route: viewRoute as! T.Route)
            
            if coordinator.children.childCoordinators.dropFirst().first == nil {
                coordinator.children.childCoordinators.append(resolved)
            } else {
                coordinator.children.childCoordinators[1] = resolved
            }
        }
    }
}

public class HamburgerRouter<T>: ObservableObject {
    private let routable: HamburgerRoutable
    private let child: HamburgerChild
    
    public func route(to route: T) {
        routable.anyRoute(to: route)
    }
    
    public var showMenu: Bool {
        get {
            return child.showMenu
        } set {
            child.showMenu = newValue
        }
    }
        
    init<U: HamburgerCoordinatable>(_ coordinator: U) {
        self.routable = HamburgerRoutable(coordinator: coordinator)
        self.child = coordinator.children
    }
}

```

but yes, this process could and should be simplified...

**Comment by jblanco-applaudostudios** [comment]
I've tried implementing the code above, as I'm trying to code a menu similar to a hamburger menu. How would I handle the routing, let's say for example if the user clicks an option in the master view, how would I be able to change it in the detail?

`final class IPadCoordinator: PadCoordinatable {
    var children = PadChild(detail: NavigationViewCoordinator(HomeCoordinator()).eraseToAnyCoordinatable(), master: NavigationViewCoordinator(ProductsCoordinator()).eraseToAnyCoordinatable())
    
    enum Route {
        case customers
        case products
    }
    
    func resolveRoute(route: Route) -> AnyCoordinatable {
        switch route {
        case .customers:
            return NavigationViewCoordinator(CustomersCoordinator()).eraseToAnyCoordinatable()
        case .products:
           return NavigationViewCoordinator(ProductsCoordinator()).eraseToAnyCoordinatable()
        }
    }
    
    func start() -> some View {
        SplashView()
    }
}`

I understand the route is used when changing to a different coordinator, routing to either .customers or .products would replace my current coordinator with a new one. Is this the correct way of implementing this?

**Comment by rundfunk47** [comment]
As per the documentation:

```
You can also fetch routers referencing coordinators that appeared earlier in the tree. For instance, you may want to switch the tab from a view that is inside the TabView.
```

So using `@EnvironmentObject var masterRouter: PadRouter<IpadCoordinator.Route>` you can change the master.

If you want the detail, well, the code I pasted above doesn't support that. You'd need to add another function:

`
public class HamburgerRouter<T, V>: ObservableObject {
    public func routeDetail(to route: V) {
    ...
`

in the router and the routable something like:
`
class HamburgerRoutable {
    var _anyRoute: (Any) -> Void
    var _anyDetailRoute: (Any) -> Void
    
    func anyRoute(to route: Any) {
        _anyRoute(route)
    }
    
    func anyDetailRoute(to route: Any) {
        _anyDetailRoute(route)
    }

    init<T: HamburgerCoordinatable>(coordinator: T) {
        _anyRoute = { viewRoute in
            let resolved = coordinator.resolveRoute(route: viewRoute as! T.Route)
            
            if coordinator.children.childCoordinators.dropFirst().first == nil {
                coordinator.children.childCoordinators.append(resolved)
            } else {
                coordinator.children.childCoordinators[1] = resolved
            }
        }

        _anyDetailRoute = { viewRoute in
            let resolved = coordinator.resolveRoute(route: viewRoute as! V.Route)
            coordinator.children.childCoordinators[0] = resolved
        }
    }
}
`
and probably also change some other details.

Also note that the code posted is quite old, so it doesn't support the newest features such as RouterStore.

**Comment by jblanco-applaudostudios** [comment]
Thank you, I was able to use this to get it to work the way I wanted.

I just have another question. 
Is it possible, for example, to route the detail to another coordinator but change the start of said coordinator? 🤔  Or would i have to create a new one for that?

What's the best current approach for this?

**Comment by rundfunk47** [comment]
I'm not 100% sure I understand what you're going for here, but I guess if you're for example using a NavigationCoordinatable you can probably do something like

```
class MyCoordinator: NavigationCoordinatable {

    init(startA: Bool) {
        self.startA = startA
    }

    @ViewBuilder func start() -> some View {
        if startA {
            StartA()
        } else {
            StartB()
        }
[...]
```

**Comment by jblanco-applaudostudios** [comment]
Thank you so much for your help! 
This project and your assistance have been really helpful for me. Love Stinsen 🎉
