### ISSUE TITLE
Unwanted popping/re-pushing when on navigation coordinator

### ISSUE THREAD

**Issue by jblanco-applaudostudios** [rundfunk47/stinsen#22]
Hello, I'm having an issue with the navigation stacks.  I have a `SidebarCoordinator` that has a `SplitviewCoordinator` inside of it (both are custom coordinators I made). The `SplitviewCoordinator` shows two `NavigationCoordinator`s side by side.  

I'm having a problem that whenever I show or hide the sidebar, if any of the navigation stacks is not on the root it will pop and then re-push the current view on said stack. Is this a known issue? Or perhaps a mistake I made while coding the coordinator view?

**Comment by rundfunk47** [comment]
Hi! Can't say I've really noticed that before no. Would it be possible for you to reproduce the issue in a small example app where I can see what's happening?

**Comment by rundfunk47** [comment]
Hi! There's a version 2.0.0 now that relies on `isActive` instead of `onAppear` to set the navigation stack, which I suspect might have been the cause of the issue. Please try it and see if it resolves it!

**Comment by jblanco-applaudostudios** [comment]
Thanks, I'm working on migrating to 2.0.0!
