### ISSUE TITLE
Memory Leaks/Cycles

### ISSUE THREAD

**Issue by savage7** [rundfunk47/stinsen#27]
I think that there are some memory leaks in Stinsen (tested with 2.0.2). They are relatively easy to reproduce.

- Open the testbed
- Login
- Logout
- Login

or

- Open the testbed
- login
- open todos
- press add
- close
- press add
- close

Outcome:
The coordinators seam to be strongly referenced and are not freed.

![image](https://user-images.githubusercontent.com/971353/134303894-e0f01bc6-d67e-42b6-924a-3c9b44537b7c.png)

There seams to be a cycle problem:

![image](https://user-images.githubusercontent.com/971353/134304017-c392f6b3-7c74-4e67-8fa1-51b21a3b1845.png)

It tried to find the root cause, like strong references in closures, but didn't find it 😿 .

**Comment by rundfunk47** [comment]
This commit should solve the problem :)

**Comment by savage7** [comment]
Tested it, it's fixed 🥇
