### ISSUE TITLE
Dismiss coordinator and pop to root

### ISSUE THREAD

**Issue by yarovoyDeveloper** [rundfunk47/stinsen#38]
Thank you for the wonderful framework
Can I kill the current coordinator and return to the first screen of the previous coordinator? 
So far, that's all I've come up with: 

@EnvironmentObject private var mainRouter: MainCoordinator.Router
@EnvironmentObject private var registrationCardRouter: RegistrationCardCoordinator.Router
    
    var body: some View {
        Text("KopilkaScreen")
            .navigationBarBackButtonHidden(true)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button(action: back) {
                        Text("Back")
                    }
                }
            }
    }
    
    func back() {
        registrationCardRouter.dismissCoordinator {
            mainRouter.popToRoot()
        }
    }

But it shows first the last screen of the stack and a moment later the first screen.  
Sorry for my English.

**Comment by yarovoyDeveloper** [comment]
Thanks, it works!
But I don't understand how)
I have 4 coordinators. Main Coordinator and 3 coordinators that lie in the same navigation stack. Being on the first screen of coordinator-4, I call mainRouter.poptoroot() and this leads to the first screen of coordinator-3 as I need it. But why? Also, if I call it on some coordinator-3 screen, I will still get to the first coordinator-3 screen.

**Comment by rundfunk47** [comment]
Hi!

Let's say you have coordinators A, B. So we might have a stack of

A A1 A2 B B1 B2

Where A1, A2, B1 and B2 are views that have been routed to from their respective coordinators A and B. Calling popToRoot will remove all views but also all child coordinators that have been routed to. So calling popToRoot on B would dismiss B1 and B2. If you had no views B1 and B2, popToRoot would do nothing. Calling popToRoot on A would remove A1 A2 B B1 B2.

**Comment by yarovoyDeveloper** [comment]
Thanks!
