### ISSUE TITLE
TabView/Coordinatable - Notify children of tab selection

### ISSUE THREAD

**Issue by LePips** [rundfunk47/stinsen#40]
It's a common feature in many apps that use a tab view with navigation view children where if the tab is tapped twice/multiple times it will pop the navigation view to the root. SwiftUI alone doesn't have this functionality but has a workaround from some people: https://stackoverflow.com/questions/60690933/swiftui-pop-to-root-view-when-selected-tab-is-tapped-again

While that example is very specific, it would be helpful to create a handler that children views of TabCoordinatable will use to detect whether the tab was selected. It is then up to the children to determine what they want to do (like popping the navigation view to root or whatever they may want).

This is a large ask but may also urge me to learn more about how Stinsen works and contribute.

**Comment by rundfunk47** [comment]
Hi! I'll check on this soon, but to be clear, how would you suggest the handler to be implemented?

**Comment by LePips** [comment]
Hi, sorry that it has been a long time for this. I honestly can't remember exactly how I thought to go about this. Because of this, I'll close this issue so it isn't outstanding and I don't even think it may be possible/give me what I want.
