### ISSUE TITLE
Use pop() inside NavigationCoordinatable

### ISSUE THREAD

**Issue by ivedeneev** [rundfunk47/stinsen#41]
Hello again! I wold like to pop back inside of coordinator. Is there any way to implement something like this?

```swift
func makeView() -> some View {
  viewModel.$switchSearchType
      .sink { [weak self] _ in
          self?.pop() // no such method
      }
      .store(in: &cancellables)
...
    return View()
}
```

**Comment by ivedeneev** [comment]
@rundfunk47 'popLast' is inaccessible due to 'internal' protection level

**Comment by rundfunk47** [comment]
Hi, just pushed a fix to main branch. Please, test if it works for you :)

**Comment by ivedeneev** [comment]
can u pls push 2.0.6 tag aswell?)

**Comment by rundfunk47** [comment]
Done

**Comment by ivedeneev** [comment]
it works! thank you
