### ISSUE TITLE
[Question] How can I pass parameters to another coordinator/viewModel

### ISSUE THREAD

**Issue by AdMeen89** [rundfunk47/stinsen#46]
Hello. At first, thanks for the great library!

I have a question but can't find the answer. Is there a way what with I can pass one or a few parameters to my "module"? 

Notes: I use the architecture which in common looks like MVVM. There are a few minor differences. But at first glance, it shouldn't affect the general way of implementing. 

So. I have an MVVM module that is used frequently through my app. For example, let it be the module helps a user to select a country. But sometimes I need to configure this module with parameters that are received from another one. Is there any way for it?

Below you can see the part of code for example.

```
final class UnauthenticatedCoordinator: BaseNavigationCoordinator {
    let stack = NavigationStack(initial: \UnauthenticatedCoordinator.start)

    @Root var start = makeStart
    @ViewBuilder func makeStart() -> some View {
        OnBoardingBuilder(router: self, di: di).view
    }

    @Route(.push) var recovery = makeRecovery
    @ViewBuilder func makeRecovery() -> some View {
        // In this place I wanna add some parameters
        SelectCountryBuilder(di: di).view()
    }
}

```

It seems a frequent task to me and I'm a little bit confused that I couldn't figure out it.

**Comment by perfaram** [comment]
Hi!
I'm not the author of Stinsen but I may be able to help. 

You can define your route builder with a parameter:
```
    @Route(.push) var recovery = makeRecovery
    @ViewBuilder func makeRecovery(_ dependency: YourDIType) -> some View {
        // In this place I wanna add some parameters
        SelectCountryBuilder(di: dependency).view()
    }
```

Then, you can route to this view using `.route(to: \.recovery, myDependency)`.

It works because of Stinsen's heavy use of generics (`.route` is actually defined with multiple overloads, many of which take a generic argument `Input`).

**Comment by AdMeen89** [comment]
@perfaram yeah! It is what I needed.
Great thanks!
