### ISSUE TITLE
[Question] ViewModel Handling

### ISSUE THREAD

**Issue by savage7** [rundfunk47/stinsen#5]
First off thanks for this library!! It seams to elegantly solve one of the most annoying SwiftUI issues :blush:

Reading this documentation it found this:
"This @EnvironmentObject can be put into a ViewModel if you wish to follow the MVVM-C Architectural Pattern."

How do you actually do this? Since a ViewModel isn't a View it has not access to EnvironmentObjects and the resolution would fail. 

Do you pass the coordinator to the ViewModel via constructor or property. Or did you find a nicer solution for this?

**Comment by rundfunk47** [comment]
Hi! Thanks 😁

Yes, you are correct. The best way I've found solving this problem is something like:

```swift
class ViewModel: ObservableObject {
    var router: NavigationRouter<Coordinator.Route>!
}
```

and in the view:

```swift
@EnvironmentObject var router: NavigationRouter<Coordinator.Route>
@ObservedObject var viewModel: ViewModel

var body: some View {
    List {  [...]  }.onAppear {
        self.viewModel.router = self.router
    }
}

```

**Comment by savage7** [comment]
Thanks for your help 😊
I created a fork which solves it for me, but honestly it's a bit messy so I will not send a PR:
https://github.com/bluesource/stinsen

General explanation why I've done this:
My architecture for SwiftUI Apps looks this:
app -> contains the Coordinators and builds the UI with its ViewModels+Business Logic
- UI Framework -> Contains all Views
- Shared Framework -> Shared Code like Models, Assets

I only use ViewModels for Screens/Scenes, all other Views use their models directly.
My goal was to completely decouple the UI Code from the Business code. I've done this to speed up Preview builds and to keep the UI code completely decoupled from the actual implementation.

My views don`t handle any navigation, only ViewModels navigate. 

My workaround:
- inject the Router in their constructor into the Resolver Container

Within my ViewModels I can then use Resolver to get the Router and navigate.

I've not found a way to inject the Router to the DI container without forking. On solution would have been to inject in in the onAppear of the Coordinator view, but this is bit to late for the Resolver resolution to work...
