### ISSUE TITLE
[Question] Is it possible to customize the NavigationCoordinatableView?

### ISSUE THREAD

**Issue by johanesriandy** [rundfunk47/stinsen#53]
I have a requirement to use Stinsen as the navigation to open a custom sheet. While currently it support to route to the view as a `modal` that will using `sheet` under the hood, we actually want to use our own implementation of the sheet. Is it possible to create a custom `NavigationCoordinatableView` for now?

I'd tried to create one but it seems that the `PresentationHelper` and some properties of the `NavigationStack` are private/internal.

**Comment by rundfunk47** [comment]
Hi! It is unfortunately not supported atm. Adding support for custom transitions is on the roadmap...
