### ISSUE TITLE
Does stinsen support installation with CocoaPods?

### ISSUE THREAD

**Issue by hdmdhr** [rundfunk47/stinsen#6]
First of all, thank you for providing such a simple and elegant way to implement coordinator pattern with SwiftUI, I have been sniffing around about this topic and your approach is the best I found.

I installed this library with **Swift Package Manager** very easily and had zero issues when using it. But my project also depends on some other third party libraries that do not support SPM, so I also had to use CocoaPods to install those. And now, for some Apple M1 chip and arm64 compilation reason, I couldn't make the project compile for both CocoaPods and SPM dependencies, so I am thinking about dropping SPM and use CocoaPods only, because I know how to make it work with CocoaPods.

So here we are back to my original question: do you currently or plan to support installation with CocoaPods? I tried searching `stinsen` on [CocoaPods.org](https://cocoapods.org/) but could not find it. Also, if you can add a `Installation` section to your readme, it would definitely help some devs to use your framework more easily.

Thanks again, for sharing this great library!

**Comment by rundfunk47** [comment]
Hi! Thanks, just happy to be able to help out other developers 😄. I haven't used CocoaPods for a while so I haven't really thought about adding support yet, but of course it makes sense to do so. I've released `1.0.6`which has support for Cocoapods, and I've also added a small `Installation` section to the readme.md 😊

**Comment by hdmdhr** [comment]
Thank you for fast response! @rundfunk47
I was just looking at your master branch so I didn't realize that you have already supported CocoaPods. But weirdly enough, I gave it a try yesterday and now, and below is the result I am getting.

![image](https://user-images.githubusercontent.com/21206584/116002266-2519a280-a5b6-11eb-997b-4ad4ef38f9c9.png)

Btw I have figured out a way to make CocoaPods and SPM work together on M1, but still, knowing it has CocoaPods support is always reassuring.

**Comment by rundfunk47** [comment]
Hi, does it work now? It takes a while for the main Cocoapods repo to index it, it seems

**Comment by hdmdhr** [comment]
@rundfunk47 Thanks for confirming! After I ran `pod repo update`, then `pod install`, it's all working! I have successfully installed Stinsen (1.0.7)! Appreciate all your helps!

**Comment by rundfunk47** [comment]
Great 👍🏼
