### ISSUE TITLE
How to pass parameters to a make func

### ISSUE THREAD

**Issue by razvanrujoiu** [rundfunk47/stinsen#68]
I have the following scenario: i want to pass parameters to a function that returns a view: 

```
@ViewBuilder
    private func makeMailComposeVC(recepients: [String], capturedImage: UIImage, completion: @escaping Action) -> some View {
        MailComposeViewController(toRecipients: recepients, capturedImage: capturedImage, didFinish: completion)
    }
```

but here it says:  "No exact matches in call to initalizer"

`@Route(.modal) var mailCompose = makeMailComposeVC
`

**Comment by savage7** [comment]
Like this:
` router.route(to: \. mailCompose, (recepients, capturedImage, ...)) `

Or better create a model for this and pass it as param.

**Comment by savage7** [comment]
roughly like this:
`    private func makeMailComposeVC(param:(recepients: [String], capturedImage: UIImage, completion: @escaping Action)) -> some View {
`

**Comment by razvanrujoiu** [comment]
That is what i needed, now it works like a charm,  thank you @savage7
