### ISSUE TITLE
[question] TabBar Button tap gesture

### ISSUE THREAD

**Issue by okstring** [rundfunk47/stinsen#73]
Hello, thank you for providing a good coordinator pattern library. 

We tried to make the TabBar Button move to the corresponding tabView root when pressed, and move to the top of the scrollView when clicked again, but we found that tapGesture does not work for the TabBar Button provided by stinsen.

```swift
@ViewBuilder func makeFirstTab(isActive: Bool) -> some View {
    VStack {
        Image("icon")
        Text("TabItem")
    }
    .onTapGesture {
        // Not working
    }
}
```

I'm looking for a way other than how to create a Custom TabBar to save resources and I was wondering if there is a better way inside the library?  

Thanks

**Comment by rundfunk47** [comment]
Closing this issue 🙂 Please comment if you have further questions or ideas!

**Comment by emartinson** [comment]
Hi, @rundfunk47 thank you for this PR. I'm wondering if anything changes since https://github.com/rundfunk47/stinsen/pull/77 ? I can't find `onTapped` in Stinsen.

Was it renamed or removed?

**Comment by rundfunk47** [comment]
We haven't had a proper release since this was merged, try the master branch?
