### ISSUE TITLE
Crash When Set Linker Other Flags With -ObjC

### ISSUE THREAD

**Issue by freakandstein** [rundfunk47/stinsen#92]
For time being, I am integrating Firebase Crashlytic and as we know that we should set Linker Other Flags with ObjC. Before I set it, my app run well, but after setting it with -ObjC, my app is crash in the first time loaded

`Could not cast value of type 'Stinsen.Transition<FeatureMain.MainCoordinator, Stinsen.RootSwitch, (), Stinsen.NavigationViewCoordinator<FeatureMain.AuthenticatedCoordinator>>' (0x1db05f130) to 'Stinsen.NavigationOutputable' (0x12d03b9f8).
2022-08-27 12:47:18.223983+0700 Geolancer[4242:4805384] Could not cast value of type 'Stinsen.Transition<FeatureMain.MainCoordinator, Stinsen.RootSwitch, (), Stinsen.NavigationViewCoordinator<FeatureMain.AuthenticatedCoordinator>>' (0x1db05f130) to 'Stinsen.NavigationOutputable' (0x12d03b9f8).`

<img width="797" alt="Screen Shot 2022-08-27 at 13 30 13" src="https://user-images.githubusercontent.com/6848453/187018102-27b745cb-22f5-4faa-a1dd-00f797d1344b.png">

There is the log that I found.

**Comment by swicaksono-appen** [comment]
Any update? I am waiting the answer from you. Thanks

**Comment by freakandstein** [comment]
Sorry, I have removed your Stinsen as my library in my app. I don't need Stinsen anymore and never.
